### ISSUE TITLE
Contacting the developer

### ISSUE THREAD

**Issue by j-dogcoder** [Gymnophoria/Arthur#30]
Hi, could the developer/owner of this project please reach out to me?

**Comment by GlitchMasta47** [comment]
You can get support quickly in the [Discord server](https://discord.gg/HW7KYG9), or describe your issue more thoroughly here instead.

**Comment by j-dogcoder** [comment]
I don't need support, I would like to talk to the owner.

**Comment by Techno-coder** [comment]
If you're unwilling to describe what you want to discuss here then you should state your preferred method of contact. The Discord server is still the fastest method to contact the developers.

**Comment by j-dogcoder** [comment]
My preferred method of contact would probably be a DM in discord. My username is J-dogcoder#0803

**Comment by j-dogcoder** [comment]
You could also email me at j.dogcoder@gmail.com

**Comment by Gymnophoria** [comment]
You didn't include your full tag, but as others have said, go ahead and join the Discord server and you can message me from there (Gymnophoria) if you really need to.

**Comment by Gymnophoria** [comment]
There's also an email in my profile 🤔 
Unsure why you needed to create an issue for this.
