### ISSUE TITLE
Using data URLs allows execution of any base64 code.

### ISSUE THREAD

**Issue by PerhapsSomeone** [Gymnophoria/Arthur#8]
Using the following command:
`a.webshot data:text/plain;base64,SGku`
renders a page with "Hi." on it.
Actually it should error out.

**Comment by PerhapsSomeone** [comment]
@Gymnophoria

**Comment by Gymnophoria** [comment]
Inexperienced developer me is curious why that's a problem? I think rendering images/text with base64 is nice; is there a vulnerability here?

**Comment by PerhapsSomeone** [comment]
Also you leak your own IP of you take a webshot of canihazip.com.

**Comment by Gymnophoria** [comment]
Fair enough, thank you for informing me of this vulnerability. Patched. :P 
And yes, IP leaks are a thing, I have some very minimal detection for that but I'm not really worried; I have a dynamic IP and generally people aren't malicious towards discord bots.

**Comment by PerhapsSomeone** [comment]
Never hurts to be careful.
No problem. =)
